# Generated by Django 4.2.20 on 2025-03-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("price_change", models.CharField(max_length=20)),
                ("price_change_percent", models.CharField(max_length=20)),
                ("weighted_avg_price", models.CharField(max_length=20)),
                ("prev_close_price", models.CharField(max_length=20)),
                ("last_price", models.CharField(max_length=20)),
                ("last_qty", models.CharField(max_length=20)),
                ("bid_price", models.CharField(max_length=20)),
                ("bid_qty", models.CharField(max_length=20)),
                ("ask_price", models.CharField(max_length=20)),
                ("ask_qty", models.CharField(max_length=20)),
                ("open_price", models.CharField(max_length=20)),
                ("high_price", models.CharField(max_length=20)),
                ("low_price", models.CharField(max_length=20)),
                ("volume", models.CharField(max_length=30)),
                ("quote_volume", models.CharField(max_length=30)),
                ("open_time", models.BigIntegerField()),
                ("close_time", models.BigIntegerField()),
                ("first_id", models.BigIntegerField()),
                ("last_id", models.BigIntegerField()),
                ("count", models.IntegerField()),
                ("fetched_at", models.DateField()),
            ],
            options={
                "ordering": ["-fetched_at", "symbol"],
                "indexes": [
                    models.Index(
                        fields=["symbol"], name="coins_ticke_symbol_49a0f8_idx"
                    ),
                    models.Index(
                        fields=["fetched_at"], name="coins_ticke_fetched_880b48_idx"
                    ),
                ],
                "unique_together": {("symbol", "fetched_at")},
            },
        ),
    ]
